### ISSUE TITLE
Some general questions

### ISSUE THREAD

**Issue by iksi4prs** [Ink230/DirectoryPredictor#5]
Hi Justin, @Ink230 
I was referred to this project by someone from the PowerShell team, as I was looking for something similar.
I tried to use it without looking at the code first, but I did watch the video.
Out of the box, without any changes, this was my experience:

1) I typed "code" like in the example video, no suggestion appears (I do have it installed)
I went back to the Readme, I wondered if I need to add extensions explicitly, 
I wish there was "Get-DirectoryPredictorOption -FileExtensions"

2)  if I type "cd ./" => it shows also "cd .gitconfig" as option (it was a file in some random directory I started to check)
but of of course .gitconfig is a file not a folder

I have 2 questions:

1) The readme says "Only files are searched and only one directory deep"
Is this just the current status, or also the planned behaviour ?
What I was looking for, and that is how I found this project, is that when I type  "cd ." it will show me all the subfolders, not history.
but if you search only files, then I guess it's not going to do it.I was thinking of also making some stats/score, e.g. when a certain subfolder is also in history, it will show higher results.Not exactly, but taking some ideas from "jump" ( https://github.com/gsamokovarov/jump )

2) Is this part of some kind of semi-official plugin, later to be merged to Powershell ?
Thanks for your help, and I'm always thankful for any FOSS.

Si.

**Comment by Ink230** [comment]
Hello @iksi4prs! :]

1. The release version is working without explicit cmdlets.
![image](https://user-images.githubusercontent.com/29797557/228097863-dacb1e90-5d6d-416e-948f-e265d55bfc35.png)
Some common things to check:
• ```Import-Module DirectoryPredictor```
• ```Set-PSReadLineOption -PredictionSource HistoryAndPlugin```
• You can run ```Get-InstalledModule``` and see if DirectoryPredictor shows up
• Did you get it from PSGallery or from your own compile?
• When you type code, you need to hit space and then type something to be matched against. Commands are not used for searching. Strings after a command are (providing they are not empty).

2. DirectoryPredictor searches, by default, for files and not folders. It is searching the directory for matches. The toggle to switch to searching for folders is in development (not sure if both should be searchable at the same time). The ```cd ./``` should be providing you with files that start with a period. 

---

1. This functionality is in development (searching folders). The pattern matching part will come after (cd .). I'm also going to include wildcard matching with *. Using . for folder views is tricky since folders can start with a period. I'm considering ```cd ?``` to break and just display all subfolders, instead of using symbols that are legal for folder or file names. Feedback welcome on what symbols to use!

2. It is not an official plugin for PowerShell. It is leveraging new experimental features that may or may not remain apart of PowerShell.

**Comment by iksi4prs** [comment]
Hi @Ink230 , 
Thanks for your detailed answers !
I've installed myself, not from PSGallery.
I will start "play" with it and with the code, and see how it goes
10x again.
